### PR TITLE
Add simple CSS cdn for basic styling on the page

### PR DESCRIPTION
**Pull request by kunaljaykam**
Simple CSS offers an automatic enhancement of our HTML, providing a cleaner and more aesthetically pleasing look without the need for custom styling. https://github.com/kevquirk/simple.css

It also adapts automatically to dark or light themes.

I have attached the screenshots of before and after integrating simple css:

Screenshot from 2024-01-10 14-50-45
Screenshot from 2024-01-10 14-50-24

### CODE REVIEW

**Comment by csev** [comment]
Thanks.   Merged and rolled into production.  I like simple CSS :)

**Comment by kunaljaykam** [comment]
I knew you would like it :). I call it magic css.

**Comment by csev** [comment]
Kind of like bootstrap without all the markup changes.

**Comment by csev** [comment]
I just sponsored @kevquirk on github :)

**Comment by kevquirk** [comment]
Thank you ♥️

**Comment by kunaljaykam** [comment]
Thank you @kevquirk for creating simple CSS. I love it.

**Pull request merged**
